# Generated by Django 2.2 on 2019-06-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190608_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='street_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
