# Generated by Django 2.2 on 2019-06-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190615_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='street_address',
            field=models.CharField(max_length=100),
        ),
    ]
