# Generated by Django 2.2.2 on 2019-07-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190702_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
